# Generated by Django 3.2.6 on 2021-12-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Poster')),
                ('year', models.CharField(max_length=5)),
                ('rating', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ['-id'],
            },
        ),
    ]
