# Generated by Django 3.2.6 on 2022-01-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Shots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nomi')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Kadr haqida')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Kadr')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'Kadr',
                'verbose_name_plural': 'Kadrlar',
            },
        ),
    ]
